version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg14
    container_name: postgres-pgvector
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
